#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SOS) += sos

sos: export COMPONENTS=${sos-components}
sos: ${sos-components-y} \
     libsel4 libelf $(libc) libcpio \
     libsel4cspace libserial libclock \
     liblwip libnfs libethdrivers \
     libsos libplatsupport libutils

